#!/usr/bin/env python3
"""
Script to automatically update the DSA repository README.md
with LeetCode problem statistics and a table of all solutions.
"""

import os
import re
from pathlib import Path
from collections import defaultdict

def extract_problem_info(folder_path):
    """Extract problem information from a problem folder's README.md."""
    readme_path = folder_path / "README.md"
    
    if not readme_path.exists():
        return None
    
    with open(readme_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Extract problem title and URL from h2 tag
    h2_match = re.search(r'<h2><a href="(https://leetcode\.com/problems/[^"]+)">([^<]+)</a></h2>', content)
    if not h2_match:
        return None
    
    url = h2_match.group(1)
    title = h2_match.group(2).strip()
    
    # Extract difficulty from badge
    difficulty_match = re.search(r"alt='Difficulty: (Easy|Medium|Hard)'", content)
    if not difficulty_match:
        difficulty = "Unknown"
    else:
        difficulty = difficulty_match.group(1)
    
    # Extract problem number from folder name
    folder_name = folder_path.name
    number_match = re.match(r'(\d+)-', folder_name)
    if number_match:
        problem_number = int(number_match.group(1))
    else:
        problem_number = 0
    
    # Find solution file
    solution_files = list(folder_path.glob("*.cpp")) + list(folder_path.glob("*.py")) + list(folder_path.glob("*.java")) + list(folder_path.glob("*.js"))
    solution_file = solution_files[0] if solution_files else None
    
    return {
        'number': problem_number,
        'title': title,
        'difficulty': difficulty,
        'url': url,
        'folder': folder_name,
        'solution_file': solution_file.name if solution_file else None
    }

def generate_readme(problems):
    """Generate the README.md content."""
    
    # Count problems by difficulty
    difficulty_counts = defaultdict(int)
    for problem in problems:
        difficulty_counts[problem['difficulty']] += 1
    
    total = len(problems)
    easy = difficulty_counts.get('Easy', 0)
    medium = difficulty_counts.get('Medium', 0)
    hard = difficulty_counts.get('Hard', 0)
    
    # Sort problems by number
    sorted_problems = sorted(problems, key=lambda x: x['number'])
    
    # Generate table rows
    table_rows = []
    for problem in sorted_problems:
        solution_link = f"[{problem['solution_file']}]({problem['folder']}/{problem['solution_file']})" if problem['solution_file'] else "N/A"
        table_rows.append(f"| {problem['number']:4d} | {problem['title'][:50]:50s} | {problem['difficulty']:8s} | {solution_link} |")
    
    table_content = "\n".join(table_rows)
    
    readme_content = f"""# LeetCode Solutions

📊 **Total Problems Solved: {total}**

🟢 Easy: {easy}
🟡 Medium: {medium}
🔴 Hard: {hard}

---

## Problem List

|    # | Problem                                         | Difficulty | Solution                                     |
| ---: | ----------------------------------------------- | ---------- | -------------------------------------------- |
{table_content}

---

## How to Add a New Problem

1. Create a new folder with the format: `{{number}}-problem-name`
2. Add your solution file (e.g., `solution.cpp`)
3. Add a `README.md` with the problem description (copy from LeetCode)
4. Commit and push - the README will automatically update!

---

## Repository Structure

```
DSA/
├── scripts/
│   └── update_readme.py
├── 0001-two-sum/
│   ├── solution.cpp
│   └── README.md
├── 0009-palindrome-number/
│   ├── palindrome-number.cpp
│   └── README.md
└── README.md
```

*This README is automatically generated by `scripts/update_readme.py`*
"""
    
    return readme_content

def main():
    """Main function to update the README."""
    # Get the repository root (DSA folder)
    repo_root = Path(__file__).parent.parent
    
    # Find all problem folders (folders that start with a number)
    problem_folders = []
    for item in repo_root.iterdir():
        if item.is_dir() and not item.name.startswith('.') and item.name != 'scripts' and item.name != '.github':
            # Check if folder name starts with a number
            if re.match(r'^\d+', item.name):
                problem_folders.append(item)
    
    # Extract problem information
    problems = []
    for folder in problem_folders:
        problem_info = extract_problem_info(folder)
        if problem_info:
            problems.append(problem_info)
    
    if not problems:
        print("No problems found!")
        return
    
    # Generate README content
    readme_content = generate_readme(problems)
    
    # Write to README.md
    readme_path = repo_root / "README.md"
    with open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme_content)
    
    print(f"README.md updated with {len(problems)} problems")
    print(f"   Easy: {sum(1 for p in problems if p['difficulty'] == 'Easy')}")
    print(f"   Medium: {sum(1 for p in problems if p['difficulty'] == 'Medium')}")
    print(f"   Hard: {sum(1 for p in problems if p['difficulty'] == 'Hard')}")

if __name__ == "__main__":
    main()